import type { ThemeDefinition, ThemeId, ThemeToken } from "./types";

const themeOptions: ReadonlyArray<{ id: ThemeId; label: string }> = [
  { id: "anchored", label: "Anchored (Default)" },
  { id: "ayu", label: "Ayu" },
  { id: "dracula", label: "Dracula" },
  { id: "catppuccin", label: "Catppuccin" },
  { id: "nord", label: "Nord" },
  { id: "light", label: "Light (Black on White)" },
];

const defaultMermaid = {
  background: "#000000",
  primaryColor: "#151515",
  primaryTextColor: "#f5f5f5",
  primaryBorderColor: "#ffffff",
  lineColor: "#8a8a8a",
  secondaryColor: "#111111",
  tertiaryColor: "#080808",
  edgeLabelBackground: "#111111",
  nodeTextColor: "#f5f5f5",
  clusterBkg: "#111111",
  clusterBorder: "#333333",
  titleColor: "#f5f5f5",
};

function tokens(
  values: Partial<Record<ThemeToken, string>>,
): Record<ThemeToken, string> {
  return {
    "color-canvas": "#000000",
    "color-text": "#f5f5f5",
    "color-text-muted": "#8a8a8a",
    "color-text-subtle": "#626262",
    "color-rule": "#242424",
    "color-row-hover": "#101010",
    "color-row-active": "#151515",
    "color-focus": "#ffffff",
    "color-danger": "#ffb4ab",
    "color-success": "#82c7a5",
    "color-menu": "#111111",
    "color-menu-border": "#333333",
    "color-selection": "#2c2c2c",
    "color-surface": "#080808",
    "color-surface-alt": "#101010",
    "color-code-text": "#e5e5e5",
    "color-mark": "#5a4b12",
    "color-backdrop": "rgb(0 0 0 / 60%)",
    "syntax-meta": "#8d8d8d",
    "syntax-heading": "#f1f1f1",
    "syntax-emphasis": "#dedede",
    "syntax-strong": "#ffffff",
    "syntax-link": "#8db7ff",
    "syntax-quote": "#c4c4c4",
    "syntax-list": "#d7a85b",
    "syntax-rule": "#777777",
    "syntax-monospace": "#d6c29a",
    "syntax-character": "#82c7a5",
    "syntax-comment": "#777777",
    "syntax-property": "#d7a85b",
    "syntax-string": "#b9d69c",
    "syntax-atom": "#b59cff",
    "syntax-invalid": "#ff8f8f",
    ...values,
  };
}

export const THEME_DEFINITIONS: Record<ThemeId, ThemeDefinition> = {
  anchored: {
    id: "anchored",
    label: "Anchored (Default)",
    tokens: tokens({}),
    mermaid: defaultMermaid,
  },
  ayu: {
    id: "ayu",
    label: "Ayu",
    tokens: tokens({
      "color-canvas": "#0b0e14",
      "color-text": "#bfbdb6",
      "color-text-muted": "#8a9199",
      "color-text-subtle": "#565b66",
      "color-rule": "#1e232b",
      "color-row-hover": "#11161d",
      "color-row-active": "#151b23",
      "color-focus": "#e6b450",
      "color-danger": "#f07178",
      "color-success": "#aad94c",
      "color-menu": "#0f131a",
      "color-menu-border": "#303640",
      "color-selection": "#263747",
      "color-surface": "#0f131a",
      "color-surface-alt": "#11161d",
      "color-code-text": "#bfbdb6",
      "color-mark": "#4d3f1b",
      "color-backdrop": "rgb(0 0 0 / 62%)",
      "syntax-meta": "#8a9199",
      "syntax-heading": "#e6b450",
      "syntax-emphasis": "#d2a6ff",
      "syntax-strong": "#f07178",
      "syntax-link": "#39bae6",
      "syntax-quote": "#8a9199",
      "syntax-list": "#e6b450",
      "syntax-rule": "#565b66",
      "syntax-monospace": "#95e6cb",
      "syntax-character": "#aad94c",
      "syntax-comment": "#626a73",
      "syntax-property": "#ffb454",
      "syntax-string": "#b8cc52",
      "syntax-atom": "#d2a6ff",
      "syntax-invalid": "#f07178",
    }),
    mermaid: {
      background: "#0b0e14",
      primaryColor: "#151b23",
      primaryTextColor: "#bfbdb6",
      primaryBorderColor: "#e6b450",
      lineColor: "#8a9199",
      secondaryColor: "#0f131a",
      tertiaryColor: "#11161d",
      edgeLabelBackground: "#0f131a",
      nodeTextColor: "#bfbdb6",
      clusterBkg: "#0f131a",
      clusterBorder: "#303640",
      titleColor: "#bfbdb6",
    },
  },
  dracula: {
    id: "dracula",
    label: "Dracula",
    tokens: tokens({
      "color-canvas": "#282a36",
      "color-text": "#f8f8f2",
      "color-text-muted": "#a7aab5",
      "color-text-subtle": "#6272a4",
      "color-rule": "#44475a",
      "color-row-hover": "#343746",
      "color-row-active": "#3a3d4e",
      "color-focus": "#bd93f9",
      "color-danger": "#ff5555",
      "color-success": "#50fa7b",
      "color-menu": "#21222c",
      "color-menu-border": "#6272a4",
      "color-selection": "#44475a",
      "color-surface": "#21222c",
      "color-surface-alt": "#343746",
      "color-code-text": "#f8f8f2",
      "color-mark": "#5f4b1e",
      "color-backdrop": "rgb(0 0 0 / 58%)",
      "syntax-meta": "#6272a4",
      "syntax-heading": "#8be9fd",
      "syntax-emphasis": "#ff79c6",
      "syntax-strong": "#f8f8f2",
      "syntax-link": "#8be9fd",
      "syntax-quote": "#f8f8f2",
      "syntax-list": "#ffb86c",
      "syntax-rule": "#6272a4",
      "syntax-monospace": "#f1fa8c",
      "syntax-character": "#50fa7b",
      "syntax-comment": "#6272a4",
      "syntax-property": "#ff79c6",
      "syntax-string": "#f1fa8c",
      "syntax-atom": "#bd93f9",
      "syntax-invalid": "#ff5555",
    }),
    mermaid: {
      background: "#282a36",
      primaryColor: "#3a3d4e",
      primaryTextColor: "#f8f8f2",
      primaryBorderColor: "#bd93f9",
      lineColor: "#a7aab5",
      secondaryColor: "#21222c",
      tertiaryColor: "#343746",
      edgeLabelBackground: "#21222c",
      nodeTextColor: "#f8f8f2",
      clusterBkg: "#21222c",
      clusterBorder: "#6272a4",
      titleColor: "#f8f8f2",
    },
  },
  catppuccin: {
    id: "catppuccin",
    label: "Catppuccin",
    tokens: tokens({
      "color-canvas": "#1e1e2e",
      "color-text": "#cdd6f4",
      "color-text-muted": "#9399b2",
      "color-text-subtle": "#6c7086",
      "color-rule": "#313244",
      "color-row-hover": "#26263a",
      "color-row-active": "#2b2b40",
      "color-focus": "#cba6f7",
      "color-danger": "#f38ba8",
      "color-success": "#a6e3a1",
      "color-menu": "#181825",
      "color-menu-border": "#45475a",
      "color-selection": "#45475a",
      "color-surface": "#181825",
      "color-surface-alt": "#26263a",
      "color-code-text": "#cdd6f4",
      "color-mark": "#5f4b1e",
      "color-backdrop": "rgb(0 0 0 / 55%)",
      "syntax-meta": "#7f849c",
      "syntax-heading": "#89b4fa",
      "syntax-emphasis": "#f5c2e7",
      "syntax-strong": "#f5e0e6",
      "syntax-link": "#89dceb",
      "syntax-quote": "#bac2de",
      "syntax-list": "#fab387",
      "syntax-rule": "#6c7086",
      "syntax-monospace": "#f9e2af",
      "syntax-character": "#a6e3a1",
      "syntax-comment": "#6c7086",
      "syntax-property": "#f38ba8",
      "syntax-string": "#a6e3a1",
      "syntax-atom": "#cba6f7",
      "syntax-invalid": "#f38ba8",
    }),
    mermaid: {
      background: "#1e1e2e",
      primaryColor: "#2b2b40",
      primaryTextColor: "#cdd6f4",
      primaryBorderColor: "#cba6f7",
      lineColor: "#9399b2",
      secondaryColor: "#181825",
      tertiaryColor: "#26263a",
      edgeLabelBackground: "#181825",
      nodeTextColor: "#cdd6f4",
      clusterBkg: "#181825",
      clusterBorder: "#45475a",
      titleColor: "#cdd6f4",
    },
  },
  nord: {
    id: "nord",
    label: "Nord",
    tokens: tokens({
      "color-canvas": "#2e3440",
      "color-text": "#eceff4",
      "color-text-muted": "#d8dee9",
      "color-text-subtle": "#7b88a1",
      "color-rule": "#434c5e",
      "color-row-hover": "#353c4a",
      "color-row-active": "#3b4252",
      "color-focus": "#88c0d0",
      "color-danger": "#bf616a",
      "color-success": "#a3be8c",
      "color-menu": "#272e39",
      "color-menu-border": "#4c566a",
      "color-selection": "#434c5e",
      "color-surface": "#272e39",
      "color-surface-alt": "#353c4a",
      "color-code-text": "#eceff4",
      "color-mark": "#5e522b",
      "color-backdrop": "rgb(0 0 0 / 55%)",
      "syntax-meta": "#81a1c1",
      "syntax-heading": "#88c0d0",
      "syntax-emphasis": "#b48ead",
      "syntax-strong": "#eceff4",
      "syntax-link": "#8fbcbb",
      "syntax-quote": "#d8dee9",
      "syntax-list": "#ebcb8b",
      "syntax-rule": "#616e88",
      "syntax-monospace": "#d08770",
      "syntax-character": "#a3be8c",
      "syntax-comment": "#616e88",
      "syntax-property": "#8fbcbb",
      "syntax-string": "#a3be8c",
      "syntax-atom": "#b48ead",
      "syntax-invalid": "#bf616a",
    }),
    mermaid: {
      background: "#2e3440",
      primaryColor: "#3b4252",
      primaryTextColor: "#eceff4",
      primaryBorderColor: "#88c0d0",
      lineColor: "#d8dee9",
      secondaryColor: "#272e39",
      tertiaryColor: "#353c4a",
      edgeLabelBackground: "#272e39",
      nodeTextColor: "#eceff4",
      clusterBkg: "#272e39",
      clusterBorder: "#4c566a",
      titleColor: "#eceff4",
    },
  },
  light: {
    id: "light",
    label: "Light (Black on White)",
    tokens: tokens({
      "color-canvas": "#ffffff",
      "color-text": "#111827",
      "color-text-muted": "#5f6368",
      "color-text-subtle": "#7a7f85",
      "color-rule": "#d9dde3",
      "color-row-hover": "#f5f6f7",
      "color-row-active": "#eef1f4",
      "color-focus": "#111827",
      "color-danger": "#b42318",
      "color-success": "#067647",
      "color-menu": "#ffffff",
      "color-menu-border": "#c6ccd4",
      "color-selection": "#cfe8ff",
      "color-surface": "#f7f8fa",
      "color-surface-alt": "#eef1f4",
      "color-code-text": "#1f2937",
      "color-mark": "#fff0a8",
      "color-backdrop": "rgb(15 23 42 / 24%)",
      "syntax-meta": "#6b7280",
      "syntax-heading": "#111827",
      "syntax-emphasis": "#7c3aed",
      "syntax-strong": "#111827",
      "syntax-link": "#155eef",
      "syntax-quote": "#4b5563",
      "syntax-list": "#b54708",
      "syntax-rule": "#6b7280",
      "syntax-monospace": "#8a4b08",
      "syntax-character": "#087443",
      "syntax-comment": "#6b7280",
      "syntax-property": "#b42318",
      "syntax-string": "#067647",
      "syntax-atom": "#7c3aed",
      "syntax-invalid": "#b42318",
    }),
    mermaid: {
      background: "#ffffff",
      primaryColor: "#eef1f4",
      primaryTextColor: "#111827",
      primaryBorderColor: "#111827",
      lineColor: "#5f6368",
      secondaryColor: "#f7f8fa",
      tertiaryColor: "#ffffff",
      edgeLabelBackground: "#ffffff",
      nodeTextColor: "#111827",
      clusterBkg: "#f7f8fa",
      clusterBorder: "#c6ccd4",
      titleColor: "#111827",
    },
  },
};

export const THEME_OPTIONS = themeOptions;
